<?php

namespace tsmith86/RedditApi ;

class Reddit 
{

	/**
	 * Reddit api connection 
	 * @var string
	 */
	private $apitHost = "HTTPS://ssl.reddit.com/api";
	
	/**
	 * Token generated by Redit Api to prevent CSRF
	 * @var [type]
	 */
	private $modHash = null ; 

	/**
	 * holds critical data to communicate with Reddit
	 * @var [type]
	 */
	private $session = null ;

	public function __construct($username = null , $password = null)
	{
		$urlLogin = $this->apitHost."/login/$username";

		$postData = "api_type=json&user=$username&passwd=$password";

		$response = $this->Connect($urlLogin,$postData);

		if(count($response->json->errors) > 0)
		{
			return $this->error(array('login failure'));
		}
	}

	function error($errors)
	{
		$message = array('error'=> $errors);

		return json_encode($message);
	}

	/**
	 * connects to reddit 
	 * @param string $url      The specific api url being used
	 * @param string $postVals string of vars beign passed to reddit
	 */
	private function Connect($url, $postVals = null)
	{

		$ch = curl_init();
		curl_setopt($ch, CURLOPT_RETURNTRANSFER , true);
		curl_setopt($ch, curlopt_cookie, "reddit_session=$this->session");
		curl_setopt($ch, CURLOPT_TIMEOUT, 3);

		if($postVals != null)
		{
			curl_setopt($ch, CURLOPT_POSTFIELDS, $postVals);
			curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
		}

		$response = json_decode(curl_exec($ch));
		curl_close($ch);

		return $response;
	}

}